local info = {
	Title = "New Year, New Shop!";
	DateCreated = {2025; 1; 4}; -- Y/M/D
	Color = Color3.fromRGB(190, 136, 28);
	ImageBanner = "rbxassetid://130437523173377";
	Active = false;
}

info.Content = {
	{"Image"; 0.3; 1/1; "rbxassetid://130437523173377"};
	{"Header"; nil; "Summary:"};
	{"NormalText"; nil; "- 🛍️ Shop now available, buy cups with Cred!"};
	{"NormalText"; nil; "- ☕ Customize the cups you serve!"};
	{"NormalText"; nil; "- 🎆 Seasonal Ingredients for the New Year!"};
	{"NormalText"; nil; "- 💎 New Unique Customers!"};
	{"NormalText"; nil; "- 💸 New Shop Items!"};
	{"NormalText"; nil; "- 📜 This Blog!"};
	{"NormalText"; nil; "- 🔧 Optimizations, fixes, and more!"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Helloooooo, internet! We just got a new update on The Hybrid Cafe, which included this blog! Could you believe it? They gave me a platform to write my own thoughts! No more writing on the basement walls!"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Anyway, one of the major features of this update is the new Shop! The shop offers a variety of cups you can buy to customize your drinks with. My personal favourite is the Kitty Cup! If you wanna get any of these cups, you'll have to pay with Cred, which are earned through every customer served. Enabling challenges also increases the Cred you earn, so if you're up for it, go for it!"};
	{"Image"; 1; 2200/998; "rbxassetid://85516763040717"};
	{"Spacing"; 5;};
	{"NormalText"; nil; [[The shop's run by the loving business couple, Daniel and Summer! They'll also visit the Cafe for a drink from time to time! I will say, they do have an interesting business practice... While Dan sells cups to people for Cred, Summer sells the Cred for something called Robux... I'm not sure what Robux is but she's told me it's a "Universal Currency". Whatever that means...]]};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Well anyway! Other than the Shop, it's also New Years season! This time around, there's now a fresh new set of ingredients themed around the season to serve to customers! Even Unique Customers will try it out sometimes. These ingredients are only here for a limited time, and after that it'll be your usual ingredients, or a new set for the season!"};
	{"Image"; 1; 1090/529; "rbxassetid://79318596882560"};
	{"Spacing"; 20;};
	{"NormalText"; nil; "Don't forget about the new decorations! Most notable decoration in my opinion is the Teapot! It has an interesting mechanic where it can fuse with another teapot.. to make another teapot! And they get BIGGER! I've spent like $2000 combining them and they don't seem to have a limit...."};
	{"Image"; 1; 1338/586; "rbxassetid://95658261925696"};
	{"Spacing"; 20;};
	{"NormalText"; nil; "More on the update, there's a few adjustments like optimizations and bigger buttons for Mobile devices... Oh! They seemed to have BUFFED the chances of getting a free gamepass from the Lucky Block by 4x! They actually have the odds written on this piece of paper. Let me take a look... WOW. That's insanely common... Well I'm definitely going to open up some Lucky Blocks after this..."};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Welp, first blog done! I'll see you when the game's updated once again! That should be next week. Signing out!"};
	{"Spacing"; 20;};
	
	
}

--[[
{"NormalText"; nil; ""};
]]

return info