local info = {
	Title = "Survival Mode and Dailies!";
	DateCreated = {2025; 1; 11}; -- Y/M/D
	Color = Color3.fromRGB(78, 99, 190);
	ImageBanner = "rbxassetid://121588336078469";
	Active = false;
}

info.Content = {
	{"Header"; nil; "Summary:"};
	{"NormalText"; nil; "- 🔥 Survival Mode! Serve until you die!"};
	{"NormalText"; nil; "- 📅 Daily Rewards"};
	{"NormalText"; nil; "- ☕ Earn Free Cups from obtaining badges!"};
	{"NormalText"; nil; "- 💎 New Unique Customer"};
	{"NormalText"; nil; "- 🎲 New Random Events"};
	{"NormalText"; nil; "- ✨ New Decorations"};
	{"NormalText"; nil; "- 🔧 Adjustments, fixes, and more!"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Hellooooo internet! Back at it again with another update, eh? There's a lot of interesting things to cover, so let's get right into it!"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "There's a new Survival Mode now available! Instead of the usual gameplay flow, you'll be getting an endless amount of customers! As you complete more orders, the difficulty increases, and customers enter at a faster rate. "};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Theoretically, you can just wait it out until you have a TON of customers! I'm currently testing that out, but it's taking a while..."};
	{"Image"; 1; 1920/762; "rbxassetid://74665798606012"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Oh, and about the ingame shop, it'll be available during the run, and the decorations refresh every 5 customers! I've been having a blast with this new gamemode, so try it out sometime!"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Anyway, other than Survival, we now have Daily Rewards! Now I can get a boost in cred to buy that Kitty Cup! There's also a free cup you can earn by logging in for 7 consecutive days! Even after getting the cup, make sure you keep your streak going!"};
	{"Image"; 1; 1230/526; "rbxassetid://78886747916598"};
	{"Spacing"; 5;};
	{"NormalText"; nil; [[Speaking of free cups, they're also giving away a free cup to anyone who completed the "Rest In Peace" or "Our Little Secret" badge! These look really cool in my opinion!]]};
	{"Image"; 1; 914/427; "rbxassetid://125360746123658"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Now, as for the regular gamemodes, there are 3 new random events that can happen throughout your run! A firework can be fired, a fire can occur in the cafe, and the island can get caught in a windstorm! I learnt the last one the hard way..."};
	{"Image"; 1; 1920/836; "rbxassetid://126120122723143"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "There's also new decorations that were in this update! There's a saxophone, microphone, and also a money bag! These bags can give a random amount of cash, and you might just get more than what you paid for!"};
	{"Image"; 1; 1072/476; "rbxassetid://130694180489008"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Oh, and I almost forgot! Kristal is now a Unique Customer! Coming from the Northern Hemisphere, she's been missing the Hybrid Cafe coffee! Make sure to serve her well, and you'll earn her sticker!"};
	{"Spacing"; 5;};
	{"NormalText"; nil; "Aaand that's all! There's a lot more to cover, but those are the most notable stuff in this update! Hope you'll enjoy it! I'm gonna be having fun with this new game mode for the next week! See you next update! Signing out!"};
	{"Spacing"; 20;};
	
}

--[[
{"NormalText"; nil; ""};
]]

return info