local info = {}

info.DisplayName = "Long Cup"
info.Description = "Labelled as XXXXL!"
info.Image = "rbxassetid://120264607018736"
info.Unlisted = false
info.CanPurchase = false

info.Price = nil

info.Premium = true
info.PremiumTitle = "Loooooong Loooooooong Cup!"
info.ProductID = 2706738124
info.PurchaseDeadline = 1739023200 -- In os.time() format

info.Model = script:FindFirstChildWhichIsA("Model")

-- MetaData
info.DateCreated = os.time({
	year = 2025;
	month = 1;
	day = 24;
})
info.CreatorName = "real_haemster"

return info