local info = {}

info.DisplayName = "Toilet Cup"
info.Description = "Ski bee D"
info.Image = "rbxassetid://82835104116418"
info.Unlisted = false
info.CanPurchase = true

info.Price = nil

info.Premium = true
info.PremiumTitle = "⛷️ + 🐝 + D"
info.ProductID = 3220969956
info.PurchaseDeadline = 1741442400 -- In os.time() format

info.Model = script:FindFirstChildWhichIsA("Model")

-- MetaData
info.DateCreated = os.time({
	year = 2025;
	month = 2;
	day = 21;
})
info.CreatorName = "real_haemster"

return info