local info = {
	["ExtraHealth"] = {
		DisplayName = "Extra Health";
		Color = Color3.fromRGB(255, 85, 111);
		ID = 915029382;
		GiftID = 2675450301;
	};
	["ExtraStamina"] = {
		DisplayName = "Extra Stamina";
		Color = Color3.fromRGB(255, 199, 103);
		ID = 915039285;
		GiftID = 2675450416;
	};
	["ExtraCash"] = {
		DisplayName = "Extra Cash";
		Color = Color3.fromRGB(94, 255, 113);
		ID = 914909471;
		GiftID = 2675450541;
	};
	["DoubleCred"] = {
		DisplayName = "Double Cred!";
		Color = Color3.fromRGB(107, 208, 255);
		ID = 1018215570;
		GiftID = 2687924326;
	};
	
	["Minigun"] = {
		DisplayName = "Minigun!";
		Color = Color3.fromRGB(147, 80, 41);
		ID = 1007802768;
		GiftID = 2676604402;
	};
	["Railgun"] = {
		DisplayName = "Railgun!";
		Color = Color3.fromRGB(1, 196, 255);
		ID = 1056292728;
		GiftID = 2836126645;
	};
}

return info