local info = {
	MainTitle = "The Hybrid Cafe";
	DisplayName = "Story Mode";
	SubTitle = {"Story Mode"; Color3.fromRGB(119, 255, 130)};
	Image = "rbxassetid://102730621776134";--"rbxassetid://118327194318885";
	Description = "Progress through the week by earning enough profit.";
	
	Gamemode = "Normal";
	Difficulty = 1;
	
	Unlisted = false;
	Disabled = false;
	AllowRanks = true;
	
	Weight = 50;
	
	--[[
	EXAMPLE:
	{
		[1] = {"EZZZ"; Color3.fromRGB(119, 255, 130)};
		[2] = {"SOOO HARDD"; Color3.fromRGB(255, 88, 88)};
	}
	]]
}

return info
