local info = {
	MainTitle = "The Hybrid Cafe";
	DisplayName = "Hard Mode";
	SubTitle = {"Hard Mode"; Color3.fromRGB(255, 88, 88)};
	Image = "rbxassetid://102730621776134";
	Description = "Overall busier workflow with stricter quotas.";
	
	Gamemode = "Normal";
	Difficulty = 2;
	
	Unlisted = false;
	Disabled = true;
	AllowRanks = true;

	Weight = 49;
	--[[
	EXAMPLE:
	{
		[1] = {"EZZZ"; Color3.fromRGB(119, 255, 130)};
		[2] = {"SOOO HARDD"; Color3.fromRGB(255, 88, 88)};
	}
	]]
}

return info
