local info = {
	MainTitle = "The Hybrid Cafe";
	DisplayName = "Survival Mode";
	SubTitle = {"Survival Mode"; Color3.fromRGB(255, 180, 88)};
	Image = "rbxassetid://121588336078469";
	Description = "Serve endless customers until you mess up.";
	
	Gamemode = "Endurance";
	Difficulty = 1;
	
	Unlisted = false;
	Disabled = false;
	AllowRanks = false;
	
	Locked = true;
	LockedMessage = "Complete Story mode to unlock.";

	Weight = 48;
	--[[
	EXAMPLE:
	{
		[1] = {"EZZZ"; Color3.fromRGB(119, 255, 130)};
		[2] = {"SOOO HARDD"; Color3.fromRGB(255, 88, 88)};
	}
	]]
}

return info
