local info = {
	{
		{
			"Keep it going.";
			"Get it higher!";
			"Doing good so far.";
			"Keep it up!";
			"Let's get higher!";
			"How long can you go?";
			"Keep it alive!";
			"Nice one."
		};
		0;
	};
	{
		{
			"Let's go!!";
			"Keep it up!";
			"Getting higher...";
			"Don't stop now!";
			"Keep it alive!";
			"Doing really good!";
			"Don't stop!";
			"The streak continues!";
		};
		7;
	};
	{
		{
			"Impressive!!";
			"Really good!";
			"That's pretty high!";
			"Wow! Nice work.";
			"Keep it alive!";
			"Higher and higher!";
			"Can't stop now!";
			"Keep it burning!";
		};
		14;
	};
	{
		{
			"Oh my god!";
			"You are insane!";
			"Don't back down now!";
			"AMAZING!";
			"How incredible!";
			"This is REALLY high!";
			"Don't give it up!";
			"Keep it FLAMING!";
		};
		21;
	};
	{
		{
			"YOU ARE THE ONE!";
			"That is CRAZY!";
			"Keep! It! Up!";
			"ABSOLUTELY MASSIVE!";
			"That's INSANE!";
			"This is SUPER high!";
			"MAKE IT HIGHER!";
			"Keep it BURSTING!";
			"You are amazing!";
			"EXTREMELY impressive!";
			"Hamburger.";
			"GREAT determination!";
			"You have determination!";
			"Don't lose it now!!";
			"That is seriously impressive.";
		};
		30;
	};
	
}

return info